CREATE TABLE module_banners (
id INT UNSIGNED NOT NULL AUTO_INCREMENT,
page_id INT UNSIGNED NOT NULL,
lang_id INT UNSIGNED NOT NULL,
date DATETIME NOT NULL ,
title VARCHAR( 255 ) NOT NULL ,
description VARCHAR( 255 ) NOT NULL ,
link VARCHAR( 255 ) NOT NULL ,
icon INT UNSIGNED NOT NULL default '0',
display TINYINT(1) NOT NULL default '0',
content TEXT NOT NULL ,
sortfield int(10) unsigned NOT NULL default '0' ,
PRIMARY KEY ( id ) 
) ENGINE=MyISAM DEFAULT CHARSET=utf8